name: Build & Release TileFinder

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "0.1.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build Mod
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TileFinder-JAR
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: TileFinder-JAR
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "**/*.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 